### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ghost** [Tomato6966/youtube-to-mp4#1]
I paste the link, the download ends, I download it to my computer, it gives an unsped error when I try to open the file, so it doesn't open

**Comment by Tomato6966** [comment]
Show screenshots, make sure to have everything `npm installed` it does work for me  and others...

**Comment by Tomato6966** [comment]
https://dl.dropboxusercontent.com/s/93aaqqa26qgd8li/Enuwd0yf3q.mp4

**Comment by Tomato6966** [comment]
Dont forget to create a folder named `videos` or re download the repo

**Comment by wioniqle-q** [comment]
> Dont forget to create a folder named `videos` or re download the repo

there is already a videos folder, there is no problem with it it does not open when I download the video

**Comment by ghost** [comment]
Okay, let me give it a try.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/69215407/125609473-945c5e99-f548-49fc-99f4-a1b06fe2ea04.png)

**Comment by Tomato6966** [comment]
install latest python

**Comment by wioniqle-q** [comment]
![image](https://user-images.githubusercontent.com/69215407/125612451-384dbd20-b83a-408b-8318-4376fa5bdcad.png)

**Comment by wioniqle-q** [comment]
![image](https://user-images.githubusercontent.com/69215407/125612477-d745dc97-1b48-4e13-af6e-2af78f687b13.png)

**Comment by ghost** [comment]
> install latest python

![image](https://user-images.githubusercontent.com/69215407/125615234-2354b90b-1a99-4379-86e2-cc401a11166b.png)
